package study2;
import java.io.*;
public class ExcepTest {
	public static void main(String args[]) {
		//尝试在两个元素大的数组里输出a[3]
		try {
			int a[]=new int[2];
			System.out.println("Success:"+a[2]);
			//如果出错 则输出错误信息
			//注意 Exception不是随便乱写的必须编译器自带且错误类型对应
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("错误:"+e);
		}
	}
}
